basePath: /
consumes:
- application/json
definitions:
  Product:
    description: Product product
    properties:
      description:
        description: description
        type: string
        x-go-name: Description
      id:
        description: ID
        format: int64
        type: integer
        x-go-name: ID
      name:
        description: name
        type: string
        x-go-name: Name
      price:
        description: price
        format: float
        type: number
        x-go-name: Price
      sku:
        description: s k u
        type: string
        x-go-name: SKU
    type: object
    x-go-package: github.com/badasukerubin/go-microservices/models
info:
  description: Documentation for Product API
  title: Product API
  version: 1.0.0
paths:
  /products:
    get:
      description: Returns a list of products
      operationId: listProducts
      responses:
        "200":
          $ref: '#/responses/productsResponse'
      tags:
      - products
    post:
      description: Adds a product
      operationId: addProduct
      responses:
        "200":
          $ref: '#/responses/noContent'
      tags:
      - products
  /products/{id}:
    delete:
      description: Delete a product
      operationId: deleteProduct
      parameters:
      - description: The ID of the product to update
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/noContent'
      tags:
      - products
    put:
      description: Updates a product
      operationId: updateProduct
      parameters:
      - description: The ID of the product to update
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          $ref: '#/responses/noContent'
      tags:
      - products
produces:
- application/json
responses:
  noContent:
    description: No content to return in the response
  productsResponse:
    description: A list of products to return in the response
    schema:
      items:
        $ref: '#/definitions/Product'
      type: array
schemes:
- http
swagger: "2.0"
